config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
  }

  resources :pools do
    member do
      match 'join', via: [:get, :post]
      get 'leaderboard', to: 'pools#leaderboard'
    end
  end

  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end

  resources :predictions, only: [:create, :update]

  get "up" => "rails/health#show", as: :rails_health_check

  root 'pages#home'
  
  get 'matches/current_round', to: 'matches#current_round'
  get '/profile', to: 'users#profile', as: 'user_profile'
  get '/profile/edit', to: 'users#edit', as: 'edit_user_profile'
  get '/users/check_username', to: 'users#check_username'

  patch '/profile', to: 'users#update', as: 'update_user_profile'
end

app/models/pool.rb
# == Schema Information
#
# Table name: pools
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :string
#  raffle_winner :string
#  isStarted     :boolean
#  isFinished    :boolean
#  isPublic      :boolean
#  prize         :string
#  user_id       :integer          not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Pool < ApplicationRecord
  belongs_to :user
  belongs_to :first_place_winner, class_name: 'User', optional: true
  belongs_to :second_place_winner, class_name: 'User', optional: true
  belongs_to :third_place_winner, class_name: 'User', optional: true
  has_and_belongs_to_many :matches
  has_and_belongs_to_many :users, join_table: :pools_users
  has_many :predictions, dependent: :destroy

  validates :title, presence: { message: "- El título es obligatorio" }
  validates :description, presence: true
  validates :user, presence: true
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  include Rails.application.routes.url_helpers

  before_action :save_current_round_matches, only: %i[new create]
  before_action :set_pool, only: %i[show edit update destroy join]
  before_action :authenticate_user!, except: %i[show index]
  before_action :authorize_pool_creation, only: %i[new create]
  before_action :load_matches, only: %i[new create edit update]

  def index
    @pools = Pool.all
    @current_user = current_user
    Rails.logger.debug "Pools: #{@pools.inspect}"
  end

  def show
    api_service = ApiFootballService.new

    @pool.matches.each do |match|
      if match.status != "FT"
        api_service.update_fixture(match.fixture_id)
        match.reload
      end
    end

    api_service.update_live_fixtures

    @pool.reload
    @matches = @pool.matches
    @user_is_creator = current_user == @pool.user if current_user
    @user_is_participant = @pool.users.include?(current_user) if current_user

    @matches.each do |match|
      if match.status == "FT"
        Prediction.recalculate_points_for_match(match)
      end
    end

    participants = @pool.users.includes(:predictions).map do |user|
      {
        id: user.id,
        email: user.email,
        predictions: user.predictions.where(pool_id: @pool.id).map do |prediction|
          {
            match_id: prediction.match_id,
            home_team_score: prediction.home_team_score,
            away_team_score: prediction.away_team_score,
            points: prediction.points,
            pool_id: prediction.pool_id
          }
        end
      }
    end

    Rails.logger.debug "Participants: #{participants}"

    current_user_data = if current_user
                          {
                            id: current_user.id,
                            predictions: current_user.predictions.where(pool_id: @pool.id).map do |p|
                              {
                                match_id: p.match_id,
                                home_team_score: p.home_team_score,
                                away_team_score: p.away_team_score,
                                points: p.points,
                                pool_id: p.pool_id
                              }
                            end
                          }
                        else
                          {}
                        end

    props = {
      pool: {
        id: @pool.id,
        title: @pool.title,
        description: @pool.description,
        raffle_winner: @pool.raffle_winner,
        isStarted: @pool.isStarted,
        isFinished: @pool.isFinished,
        isPublic: @pool.isPublic,
        prize: @pool.prize,
        user_id: @pool.user_id,
        created_at: @pool.created_at,
        updated_at: @pool.updated_at,
        matches: @matches.map do |match|
          {
            id: match.id,
            home_team: match.home_team,
            home_team_logo: match.home_team_logo,
            away_team: match.away_team,
            away_team_logo: match.away_team_logo,
            date: match.date,
            home_team_score: match.home_team_score,
            away_team_score: match.away_team_score,
            status: match.status,
            elapsed: match.elapsed
          }
        end,
        participants: participants
      },
      userIsCreator: @user_is_creator || false,
      userIsParticipant: @user_is_participant || false,
      currentUser: current_user_data
    }.to_json

    Rails.logger.debug "Props: #{props}"

    @props = props
  end

  def new
    @pool = Pool.new
    save_current_round_matches
    @matches = get_current_round_matches
    Rails.logger.debug "Matches loaded: #{@matches.inspect}" # Línea de depuración
  end
  
  def create
    authorize Pool
    logger.debug "Entering PoolsController#create"
    logger.debug "Pool Params: #{pool_params.inspect}"
    logger.debug "Current User: #{current_user.inspect}"

    @pool = current_user.pools.build(pool_params)
    @pool.user = current_user
    logger.debug "Pool Built: #{@pool.inspect}"

    # Filtrar valores vacíos y convertir a enteros
    match_ids = pool_params[:match_ids].reject(&:blank?).map(&:to_i)
    logger.debug "Match IDs: #{match_ids}"

    matches = Match.where(id: match_ids)
    logger.debug "Matches Found: #{matches.pluck(:id)}"
    logger.debug "Matches Count: #{matches.count}"

    respond_to do |format|
      if @pool.save
        @pool.matches << matches
        format.html { redirect_to @pool, notice: "Pool was successfully created." }
        format.json { render :show, status: :created, location: @pool }
      else
        @matches = get_current_round_matches
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @matches = get_current_round_matches
  end

  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to @pool, notice: "Pool was successfully updated." }
        format.json { render :show, status: :ok, location: @pool }
      else
        @matches = get_current_round_matches
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pool.destroy!
    respond_to do |format|
      format.html { redirect_to pools_url, notice: "Pool was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    @pool.users << current_user unless @pool.users.include?(current_user)
    redirect_to @pool, notice: "¡Listo! Ahora eres parte de la quiniela."
  end

  def leaderboard
    @pool = Pool.find(params[:id])
    @participants = @pool.users.select("users.*, SUM(predictions.points) AS total_points")
                              .left_joins(:predictions)
                              .where("predictions.pool_id IS NULL OR predictions.pool_id = ?", @pool.id)
                              .group("users.id")
                              .order("total_points DESC")

    respond_to do |format|
      format.html do
        props = {
          pool: {
            id: @pool.id,
            title: @pool.title,
            description: @pool.description,
            prize: @pool.prize,
          },
          participants: @participants.map do |participant|
            {
              id: participant.id,
              email: participant.email,
              username: participant.username,
              first_name: participant.first_name,
              last_name: participant.last_name,
              phone: participant.phone,
              profile_picture_url: participant.profile_picture.attached? ? url_for(participant.profile_picture) : nil,
              total_points: participant.total_points,
              predictions: participant.predictions.where(pool: @pool).map do |prediction|
                {
                  match_id: prediction.match_id,
                  home_team_score: prediction.home_team_score,
                  away_team_score: prediction.away_team_score,
                  points: prediction.points,
                  pool_id: prediction.pool_id
                }
              end
            }
          end
        }.to_json

        render html: "<div id='react-root' data-props='#{props}'></div>".html_safe
      end
      format.json do
        render json: {
          pool: {
            id: @pool.id,
            title: @pool.title,
            description: @pool.description,
            prize: @pool.prize,
          },
          participants: @participants.map do |participant|
            {
              id: participant.id,
              email: participant.email,
              username: participant.username,
              first_name: participant.first_name,
              last_name: participant.last_name,
              phone: participant.phone,
              profile_picture_url: participant.profile_picture.attached? ? url_for(participant.profile_picture) : nil,
              total_points: participant.total_points,
              predictions: participant.predictions.where(pool: @pool).map do |prediction|
                {
                  match_id: prediction.match_id,
                  home_team_score: prediction.home_team_score,
                  away_team_score: prediction.away_team_score,
                  points: prediction.points,
                  pool_id: prediction.pool_id
                }
              end
            }
          end
        }
      end
    end
  end

  private

    def set_pool
      @pool = Pool.find_by(id: params[:id])
      unless @pool
        Rails.logger.error "Pool with ID #{params[:id]} not found"
        flash[:alert] = "Pool not found"
        redirect_to root_path
      end
    end

    def pool_params
      params.require(:pool).permit(:title, :description, :raffle_winner, :isStarted, :isFinished, :isPublic, :prize, match_ids: [])
    end

    def authorize_pool_creation
      authorize Pool
    rescue Pundit::NotAuthorizedError
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(root_path)
    end

    def get_current_round_matches
      service = ApiFootballService.new
      season = 2024
      today = Date.today
      start_of_week = today.beginning_of_week(:monday)
      end_of_week = today.end_of_week(:sunday)
      league = params[:league_id] || 772  # Obtener el ID de la liga de los parámetros de la URL
    
      logger.debug "Fetching fixtures from #{start_of_week} to #{end_of_week} for league #{league}"
    
      response = service.fixtures(season, start_of_week, end_of_week, league)
      logger.debug "API response: #{response.inspect}"
    
      if response.is_a?(Hash) && response["response"].present?
        fixture_ids = response["response"]
                      .select { |match| match.dig("fixture", "status", "short") == "NS" }

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_with(url: predictions_path, local: true) do |form| %>
  <% @pool.matches.each do |match| %>
    <%= hidden_field_tag "prediction[pool_id][]", @pool.id %>
    <%= hidden_field_tag "prediction[match_id][]", match.id %>

    <div>
      <label>Match: <%= "#{match.home_team} vs #{match.away_team}" %></label>
    </div>

    <div>
      <label>Home Team Score</label>
      <%= number_field_tag "prediction[home_team_score][]" %>
    </div>

    <div>
      <label>Away Team Score</label>
      <%= number_field_tag "prediction[away_team_score][]" %>
    </div>
  <% end %>

  <%= form.submit "Submit Predictions" %>
<% end %>

app/views/pools/_pool.html.erb
<div id="<%= dom_id pool %>">
  <p>
    <strong>Title:</strong>
    <%= pool.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= pool.description %>
  </p>

  <p>
    <strong>Raffle winner:</strong>
    <%= pool.raffle_winner %>
  </p>

  <p>
    <strong>Isstarted:</strong>
    <%= pool.isStarted %>
  </p>

  <p>
    <strong>Isfinished:</strong>
    <%= pool.isFinished %>
  </p>

  <p>
    <strong>Ispublic:</strong>
    <%= pool.isPublic %>
  </p>

  <p>
    <strong>Prize:</strong>
    <%= pool.prize %>
  </p>

  <p>
    <strong>User:</strong>
    <%= pool.user_id %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= pool.created_at %>
  </p>

  <%= link_to 'Ver Quiniela', pool %>

</div>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render "form", pool: @pool %>

<br>

<div>
  <%= link_to "Show this pool", @pool %> |
  <%= link_to "Back to pools", pools_path %>
</div>

app/views/pools/index.html.erb
<% props = {
  pools: @pools.map { |pool| { id: pool.id, title: pool.title, description: pool.description, user_id: pool.user_id, prize: pool.prize, created_at: pool.created_at, updated_at: pool.updated_at, isPublic: pool.isPublic, isFinished: pool.isFinished } },
  notice: notice,
  userSignedIn: user_signed_in?,
  currentUser: current_user ? { id: current_user.id, admin: current_user.admin? } : nil,
  csrfToken: form_authenticity_token
}.to_json %>

<div id="react-root" data-props="<%= props %>"></div>
<%= javascript_pack_tag 'application' %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

app/views/pools/leaderboard.html.erb
<% props = {
  pool: {
    id: @pool.id,
    title: @pool.title,
    description: @pool.description,
    prize: @pool.prize,
    participants: @participants.map do |participant|
      {
        id: participant.id,
        email: participant.email,
        username: participant.username,
        first_name: participant.first_name,
        last_name: participant.last_name,
        phone: participant.phone,
        profile_picture_url: participant.profile_picture.attached? ? url_for(participant.profile_picture) : nil,
        total_points: participant.total_points,
        predictions: participant.predictions.where(pool: @pool).map do |prediction|
          {
            match_id: prediction.match_id,
            home_team_score: prediction.home_team_score,
            away_team_score: prediction.away_team_score,
            points: prediction.points,
            pool_id: prediction.pool_id
          }
        end
      }
    userSignedIn: user_signed_in?,
    end
  }
}.to_json %>

<div id="react-root" data-props="<%= props %>"></div>
<%= javascript_pack_tag 'application' %>

app/views/pools/new.html.erb
<!-- app/views/pools/new.html.erb -->
<h1>New pool</h1>

<%= form_with(model: @pool, local: true) do |form| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>
      <ul>
        <% @pool.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class = "field">
    <%= form.label :prize %>
    <%= form.text_area :prize %>
  </div>

  <div class="field">
    <%= form.label :matches %>
    <div>
      <% Match.all.each do |match| %>
        <div>
          <%= check_box_tag "pool[match_ids][]", match.id, @pool.matches.include?(match) %>
          <%= label_tag "pool_match_ids_#{match.id}", "#{match.home_team} vs #{match.away_team} - #{match.date}" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<div>
  <%= link_to "Back to pools", pools_path %>
</div>

app/views/pools/show.html.erb
<% props = {
  pool: {
    id: @pool.id,
    title: @pool.title,
    description: @pool.description,
    raffle_winner: @pool.raffle_winner,
    isStarted: @pool.isStarted,
    isFinished: @pool.isFinished,
    isPublic: @pool.isPublic,
    prize: @pool.prize,
    user_id: @pool.user_id,
    created_at: @pool.created_at,
    updated_at: @pool.updated_at,
    matches: @matches.map { |match| { 
      id: match.id, 
      home_team: match.home_team, 
      home_team_logo: match.home_team_logo,
      away_team: match.away_team, 
      away_team_logo: match.away_team_logo,
      date: match.date, 
      venue: match.venue,
      home_team_score: match.home_team_score,
      away_team_score: match.away_team_score,
      status: match.status,
      elapsed: match.elapsed,
    } },
    participants: @pool.users.includes(:predictions).map { |user| 
      { 
        id: user.id, 
        email: user.email,
        first_name: user.first_name,
        profile_picture_url: user.profile_picture.attached? ? url_for(user.profile_picture) : nil,
        predictions: user.predictions.where(pool_id: @pool.id).map { |prediction|
          { 
            match_id: prediction.match_id, 
            home_team_score: prediction.home_team_score, 
            away_team_score: prediction.away_team_score, 
            points: prediction.points,
            pool_id: prediction.pool_id
          } 
        } 
      } 
    }
  },
  notice: flash[:notice],
  userIsCreator: @user_is_creator || false,
  userIsParticipant: @user_is_participant || false,
  currentUser: current_user ? {
    id: current_user.id,
    predictions: current_user.predictions.where(pool_id: @pool.id).map { |prediction| {
      id: prediction.id,
      match_id: prediction.match_id, 
      home_team_score: prediction.home_team_score, 
      away_team_score: prediction.away_team_score,
      points: prediction.points,
      home_team_logo: prediction.match.home_team_logo,
      away_team_logo: prediction.match.away_team_logo,
      pool_id: prediction.pool_id
    } },
    admin: current_user.admin?
  } : nil,
  userSignedIn: user_signed_in?,
  csrfToken: form_authenticity_token
}.to_json %>

<div id="react-root" data-props="<%= props %>"></div>
<%= javascript_pack_tag 'application' %>